export const PACKAGE_1_PRICE_BEFORE_DISCOUNT = 99;
export const PACKAGE_1_PRICE_AFTER_DISCOUNT = 45;
export const PACKAGE_2_PRICE_BEFORE_DISCOUNT = 79;
export const PACKAGE_2_PRICE_AFTER_DISCOUNT = 35;
